# Generated by Django 5.2 on 2025-04-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='git_repo',
        ),
        migrations.AddField(
            model_name='presets',
            name='git_repo',
            field=models.CharField(default='no repo', max_length=100),
        ),
    ]
